implemented deleting variables

diff --git a/dotenv-editor b/dotenv-editor
--- a/dotenv-editor
+++ b/dotenv-editor
@@ -175,7 +175,39 @@ function updateVariable() {
         8 80 "$OLD" \
         3>&1 1>&2 2>&3)
 
-    if [ "$OLD" != "$NEW" ]; then
+
+    # Value is empty
+    if [[ "$NEW" == "" || "$NEW" == "\"\"" ]]; then
+        echo "Empty $KEY: $OLD => Should delete?" >> $LOG_FILE;
+
+        $DIALOG --title "Delete variable" \
+        --clear \
+        --yesno "Are you sure you want to delete variable \"$KEY\"?" 7 60
+
+
+        # Get exit status
+        # 0 means user hit [yes] button.
+        # 1 means user hit [no] button.
+        # 255 means user hit [Esc] key.
+        response=$?
+        case $response in
+           0)
+                echo "Delete variable: filter variable and overwrite file." >> $LOG_FILE
+                CMD=`cat $DOTENV_FILE_TMP | grep -v "$KEY=" > /tmp/dotenv-editor.tmp && cp /tmp/dotenv-editor.tmp $DOTENV_FILE_TMP`
+
+                source $DOTENV_FILE_TMP
+                ;;
+           1)
+                echo "Keep variable => Do nothing." >> $LOG_FILE
+                ;;
+           255)
+                echo "[ESC] key pressed." >> $LOG_FILE
+                ;;
+        esac
+
+
+    # Value is different
+    elif [ "$OLD" != "$NEW" ]; then
         echo "Updating $KEY: $OLD => $NEW" >> $LOG_FILE;
 
         # When quotes are enabled
@@ -194,6 +226,7 @@ function updateVariable() {
         # Resource the file to update the global variables
         source $DOTENV_FILE_TMP
 
+    # Otherwise nothing happened.
     else
         echo "No change $KEY: $OLD => $NEW" >> $LOG_FILE;
     fi
